version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: build/server.Dockerfile
    image: server:latest
    container_name: server
    ports:
      - "8090:8080" # Host:Container
    environment:
      - SERVER_CONFIG_FILE=config/server.yaml
    networks:
      - pow_network

  client:
    build:
      context: .
      dockerfile: build/client.Dockerfile
    image: client:latest
    container_name: client
    depends_on:
      - server
    environment:
      - CLIENT_CONFIG_FILE=config/client.yaml
      - ADDRESS=server:8080
    networks:
      - pow_network

networks:
  pow_network:
    driver: bridge