openapi: 3.0.0
info:
  title: PoW API
  description: Proof of Work API
  version: 1.0.0
servers:
- url: http://localhost:8080/api
paths:
  /pow/challenge:
    get:
      summary: Request a new challenge
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChallengeResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /pow/solve:
    post:
      summary: Send challenge solution
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SolveRequest'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SolveResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    SolveRequest:
      required:
      - challenge
      - solution
      type: object
      properties:
        challenge:
          $ref: '#/components/schemas/Challenge'
        solution:
          $ref: '#/components/schemas/Solution'

    ChallengeResponse:
      required:
      - challenge
      - difficulty
      type: object
      properties:
        challenge:
          $ref: '#/components/schemas/Challenge'
        difficulty:
          $ref: '#/components/schemas/Difficulty'
      example:
        difficulty: 0
        challenge: challenge
    SolveResponse:
      required:
      - quote
      type: object
      properties:
        quote:
          $ref: '#/components/schemas/Quote'
      example:
        quote: quote
    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          $ref: '#/components/schemas/Error'

    Challenge:
      type: string
      description: required challenge
    Solution:
      type: string
      description: challenge solution
    Difficulty:
      type: integer
      description: difficulty of the challenge
    Quote:
      type: string
      description: result quote
    Error:
      type: object
      required:
        - text
      properties:
        text:
          type: string
